/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alex.pe.cpresentacion;
import com.alex.pe.cmodelo.TipoDocumento;
import com.alex.pe.cnegocio.TipoDocumentoBO;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class JPanelTipoDocumento extends javax.swing.JPanel {
  TipoDocumentoBO tdbo = new TipoDocumentoBO();
  TipoDocumento td = new TipoDocumento();
  String IdTipoDocumento;
    
    
    public JPanelTipoDocumento()throws SQLException  {
           initComponents();
           listarTipoDocumento();
    }
     public void listarTipoDocumento()throws SQLException{
         tdbo.ListarTipoDOcumento(tableTipoDocumento);
     }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTipoDocumento = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTipoDocumento = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        Textnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Textsigla = new javax.swing.JTextField();
        Textorden = new javax.swing.JTextField();
        Textestado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Textfechaactualizacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnelminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        jPanelTipoDocumento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRUT TIPO DOCUMENTO");
        jPanelTipoDocumento.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 220, 60));

        tableTipoDocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableTipoDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTipoDocumentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTipoDocumento);

        jPanelTipoDocumento.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel2.setText("NOMBRE");
        jPanelTipoDocumento.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, 30));

        Textnombre.setBorder(null);
        jPanelTipoDocumento.add(Textnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 350, 30));

        jLabel3.setText("SIGLA");
        jPanelTipoDocumento.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jLabel4.setText("ORDEN");
        jPanelTipoDocumento.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        Textsigla.setBorder(null);
        jPanelTipoDocumento.add(Textsigla, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 350, 30));

        Textorden.setBorder(null);
        Textorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextordenActionPerformed(evt);
            }
        });
        jPanelTipoDocumento.add(Textorden, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 350, 30));

        Textestado.setBorder(null);
        jPanelTipoDocumento.add(Textestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 350, 30));

        jLabel5.setText("ESTADO");
        jPanelTipoDocumento.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        Textfechaactualizacion.setBorder(null);
        jPanelTipoDocumento.add(Textfechaactualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 350, 30));

        jLabel6.setText("FECHA ACTUALIZACION");
        jPanelTipoDocumento.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 160, -1));

        btnlimpiar.setBackground(new java.awt.Color(153, 239, 243));
        btnlimpiar.setText("Eliminar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanelTipoDocumento.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, -1, -1));

        btnguardar.setText("guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanelTipoDocumento.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, -1, -1));

        btnmodificar.setText("modificar");
        jPanelTipoDocumento.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, -1, -1));

        btnelminar.setText("eliminar");
        btnelminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelminarActionPerformed(evt);
            }
        });
        jPanelTipoDocumento.add(btnelminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 350, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 350, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 350, 50));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 350, 50));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 350, 50));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 350, 50));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 350, 50));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 350, 50));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanelTipoDocumento.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 350, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextordenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextordenActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
      Textnombre.setText("");
      Textsigla.setText("");
      Textorden.setText("");
      Textestado.setText("");
      Textfechaactualizacion.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       try {

      td.setNombre(Textnombre.getText());
      td.setEstado(Textestado.getText());
      td.setOrden(Integer.parseInt(Textestado.getText()));
      td.setSigla(Textsigla.getText());
      td.setFechaActualizacion( Textfechaactualizacion.getText());
      tdbo.agregarTipoDocomento(td); 
      listarTipoDocumento();
      JOptionPane.showMessageDialog(null, ":) se guardo corectamente");
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Error: al guardar Tipo documento ");

    }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void tableTipoDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTipoDocumentoMouseClicked
      int seleccion = tableTipoDocumento.rowAtPoint(evt.getPoint());
      IdTipoDocumento =  tableTipoDocumento.getValueAt(seleccion, 0)+"";
      
      Textnombre.setText(tableTipoDocumento.getValueAt(seleccion, 1) + "");
      Textsigla.setText(tableTipoDocumento.getValueAt(seleccion, 2) + "");
      Textorden.setText(tableTipoDocumento.getValueAt(seleccion, 3) + "");
      Textestado.setText(tableTipoDocumento.getValueAt(seleccion, 4) + "");
      Textfechaactualizacion.setText(tableTipoDocumento.getValueAt(seleccion, 5) + "");
              
              
              
              
        System.out.println(seleccion);
    }//GEN-LAST:event_tableTipoDocumentoMouseClicked

    private void btnelminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelminarActionPerformed
       try {
           TipoDocumento td = new TipoDocumento();
           td.setIdTipoDocumento(Integer.parseInt(IdTipoDocumento));
           tdbo.eliminarTipoDocomento(td);
           listarTipoDocumento();
       } catch (Exception alex ) {
      JOptionPane.showMessageDialog(null, "Error:"+ alex.getMessage());
       }
    }//GEN-LAST:event_btnelminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Textestado;
    private javax.swing.JTextField Textfechaactualizacion;
    private javax.swing.JTextField Textnombre;
    private javax.swing.JTextField Textorden;
    private javax.swing.JTextField Textsigla;
    private javax.swing.JButton btnelminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelTipoDocumento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable tableTipoDocumento;
    // End of variables declaration//GEN-END:variables

    

    
}
