/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alex.pe.cpresentacion;

/**
 *
 * @author Soporte
 */
public class JPanelCalculadora extends javax.swing.JPanel {

    /**
     * Creates new form JPanelCalculadora
     */
    public JPanelCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TextFieldresultado = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel1.setText("calculadora");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 25, -1, -1));

        TextFieldresultado.setFont(new java.awt.Font("Trebuchet MS", 3, 48)); // NOI18N
        TextFieldresultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextFieldresultado.setText("0");
        TextFieldresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldresultadoActionPerformed(evt);
            }
        });
        jPanel1.add(TextFieldresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 54, 388, 125));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton4.setText("cc");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, 60));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton5.setText("%");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, 60));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton9.setText("ce");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 70, 60));

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton13.setText("/");
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 70, 60));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton6.setText("9");
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 70, 60));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 60));

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton10.setText("8");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 70, 60));

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton14.setText("*");
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 70, 60));

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton11.setText("5");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 70, 60));

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton15.setText("-");
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 70, 60));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton8.setText("6");
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 70, 60));

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton12.setText("4");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 60));

        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton16.setText("2");
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 70, 60));

        jButton17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton17.setText("+");
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 70, 60));

        jButton18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton18.setText("3");
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 70, 60));

        jButton19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton19.setText("1");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, 60));

        jButton20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton20.setText("0");
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 70, 60));

        jButton21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton21.setText("=");
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 70, 60));

        jButton22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton22.setText(".");
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 70, 60));

        jButton23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton23.setText("j");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldresultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldresultadoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldresultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
