/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.alex.pe.cpresentacion;

import java.awt.BorderLayout;

/**
 *
 * @author Soporte
 */
public class NewJFrameprincipal extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameprincipal
     */
    public NewJFrameprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btncalculadoracontadort = new javax.swing.JMenu();
        btnmenucalculadora = new javax.swing.JMenuItem();
        btnmenucontador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        btnmenuTipoDocumento = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion en java Swing");

        Principal.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PrincipalLayout = new javax.swing.GroupLayout(Principal);
        Principal.setLayout(PrincipalLayout);
        PrincipalLayout.setHorizontalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        PrincipalLayout.setVerticalGroup(
            PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 255, 255));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 0));

        btncalculadoracontadort.setText("Aplicaciones");
        btncalculadoracontadort.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                btncalculadoracontadortComponentMoved(evt);
            }
        });

        btnmenucalculadora.setText("calculadora");
        btnmenucalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenucalculadoraActionPerformed(evt);
            }
        });
        btncalculadoracontadort.add(btnmenucalculadora);

        btnmenucontador.setText("contador");
        btnmenucontador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenucontadorActionPerformed(evt);
            }
        });
        btncalculadoracontadort.add(btnmenucontador);

        jMenuBar1.add(btncalculadoracontadort);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("Mantenimiento");

        btnmenuTipoDocumento.setText("TipoDocumento");
        btnmenuTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuTipoDocumentoActionPerformed(evt);
            }
        });
        jMenu1.add(btnmenuTipoDocumento);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("jMenu3");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmenucalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenucalculadoraActionPerformed
      JPanelCalculadora cal = new JPanelCalculadora();
      cal.setSize (1200, 700);
      cal.setLocation (0,0);
      Principal.removeAll();
      Principal.add(cal,BorderLayout.CENTER);
      Principal.revalidate();
      Principal.repaint();
    }//GEN-LAST:event_btnmenucalculadoraActionPerformed

    private void btnmenucontadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenucontadorActionPerformed
      JPanelContador cont = new JPanelContador();
      cont.setSize (1200, 700);
      cont.setLocation (0,0);
      Principal.removeAll();
      Principal.add(cont,BorderLayout.CENTER);
      Principal.revalidate();
      Principal.repaint();
    }//GEN-LAST:event_btnmenucontadorActionPerformed

    private void btncalculadoracontadortComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btncalculadoracontadortComponentMoved
      
    }//GEN-LAST:event_btncalculadoracontadortComponentMoved

    private void btnmenuTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuTipoDocumentoActionPerformed
      JPanelTipoDocumento td = new JPanelTipoDocumento();
      td.setSize (1022, 551);
      td.setLocation (0,0);
      Principal.removeAll();
      Principal.add(td,BorderLayout.CENTER);
      Principal.revalidate();
      Principal.repaint();
    }//GEN-LAST:event_btnmenuTipoDocumentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Principal;
    private javax.swing.JMenu btncalculadoracontadort;
    private javax.swing.JMenuItem btnmenuTipoDocumento;
    private javax.swing.JMenuItem btnmenucalculadora;
    private javax.swing.JMenuItem btnmenucontador;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
